version: 2

sources:
  - name: raw
    schema: gwz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of greenweez
        columns:
          - name: date _date
            description: the date of purchase
        tests:
          - unique: { column_name: "(orders_id || '-' pdt_id)" }
      - name: product
        identifier: raw_gz_product
        description: products of greenweez
        columns:
          - name: products_id
            description: primary key of the table
            tests:
              - unique
              - not_null
      - name: ship
        identifier: raw_gz_ship
        description: ships of greenweez
        columns:
          - name: orders_id
            description: primary key
            tests:
              - unique
              - not_null